@base_url = http://localhost:8100/api
@content_tyoe = application/json

# @name login
POST {{base_url}}/auth/login
Content-Type: {{content_tyoe}}

{
    "username": "07770374910",
    "password": "1234"
}

### 

@access_token = {{login.response.body.$.access_token}}

GET {{base_url}}/admin/organizations
Authorization: Bearer {{access_token}}

###